version: '2'
services:
    katalog-app:
        image: katalog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://katalog-postgresql:5432/katalog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    katalog-postgresql:
        extends:
            file: postgresql.yml
            service: katalog-postgresql
